<?xml version="1.0" encoding="utf-8"?>
<ClassDiagram MajorVersion="1" MinorVersion="1">
  <Class Name="Tekla.Structures.Model.ContourPlate">
    <Position X="0.5" Y="9.75" Width="2.25" />
    <Compartments>
      <Compartment Name="Nested Types" Collapsed="false" />
    </Compartments>
    <NestedTypes>
      <Enum Name="Tekla.Structures.Model.ContourPlate.ContourPlateTypeEnum">
        <TypeIdentifier />
      </Enum>
    </NestedTypes>
    <TypeIdentifier />
  </Class>
  <Class Name="Tekla.Structures.Model.Part">
    <Position X="2.5" Y="0.5" Width="3.5" />
    <Compartments>
      <Compartment Name="Nested Types" Collapsed="false" />
    </Compartments>
    <NestedTypes>
      <Enum Name="Tekla.Structures.Model.Part.CastUnitTypeEnum">
        <TypeIdentifier />
      </Enum>
    </NestedTypes>
    <TypeIdentifier />
    <Lollipop Position="0.2" />
  </Class>
  <Class Name="Tekla.Structures.Model.PolyBeam">
    <Position X="3.5" Y="9.75" Width="2" />
    <Compartments>
      <Compartment Name="Nested Types" Collapsed="false" />
    </Compartments>
    <NestedTypes>
      <Enum Name="Tekla.Structures.Model.PolyBeam.PolyBeamTypeEnum">
        <TypeIdentifier />
      </Enum>
    </NestedTypes>
    <TypeIdentifier />
  </Class>
  <Class Name="Tekla.Structures.Model.Beam">
    <Position X="6.5" Y="9.75" Width="2.75" />
    <Compartments>
      <Compartment Name="Nested Types" Collapsed="false" />
    </Compartments>
    <NestedTypes>
      <Enum Name="Tekla.Structures.Model.Beam.BeamTypeEnum">
        <TypeIdentifier />
      </Enum>
    </NestedTypes>
    <TypeIdentifier />
  </Class>
  <Class Name="Tekla.Structures.Analysis.Analysis">
    <Position X="13.75" Y="7" Width="3.5" />
    <TypeIdentifier />
  </Class>
  <Class Name="Tekla.Structures.Analysis.AnalysisArea">
    <Position X="13.5" Y="9.5" Width="3.25" />
    <TypeIdentifier />
  </Class>
  <Font Name="Segoe UI" Size="9" />
</ClassDiagram>